name: Pulumi
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Installing project dependencies
        run: |
          npm ci
      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Login to Pulumi state on Azure and preview changes
        run: |
          pulumi login azblob://pulumi-state-bucket
          pulumi stack select ${{ vars.STACK_NAME }}
          pulumi preview
        env:
          AZURE_STORAGE_ACCOUNT: ${{ vars.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }} 
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }} 
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }} 
          MONGO_URI: ${{ secrets.MONGO_URI }} 
          MONGO_PROD_URI: ${{ secrets.MONGO_PROD_URI }}
